### ISSUE TITLE
Changing host name

### ISSUE THREAD

**Issue by dalareo** [wso2/docker-is#1]
Hi,
I've changed host name property from default "localhost" in carbon.xml file but, how can I make changes apply in running docker container??

Environment variables are not available using

```
-e HOSTNAME="whatever.com"
```

**Comment by imesh** [comment]
@dalareo Currently environment variables based configurations are not possible out of the box. You may need to write a bash script to read environment variables and update the relevant configuration files. 

Anyway, it would be not possible to change configurations in a running container. For a configuration change to apply we need to restart the Carbon server. To restart the server we need to restart the container.

**Comment by dalareo** [comment]
Setting it with environment variables would be niiiiiiiice!

**Comment by imesh** [comment]
One option to handle this would be to use a volume mount for the configuration folder. We are now using a similar approach on Kubernetes using ConfigMaps.
