### ISSUE TITLE
wso2server.sh No such file or directory

### ISSUE THREAD

**Issue by paolantoni** [wso2/docker-is#12]
`
# docker-compose logs -f --tail=200 identity-server
Attaching to pattern1_identity-server_1
identity-server_1  | Initializing wso2is-5.3.0 in default profile on default platform...
identity-server_1  | Going to sleep for 10s...
identity-server_1  | Successfully updated localMemberHost with 172.21.0.3
identity-server_1  | Creating directory /mnt/172.21.0.3
identity-server_1  | Creating symlink [Target] /mnt/wso2is-5.3.0, [Link] /mnt/172.21.0.3/wso2is-5.3.0
identity-server_1  | Copying artifacts in /mnt/wso2-artifacts to /mnt/172.21.0.3/wso2is-5.3.0
identity-server_1  | Starting wso2is-5.3.0 with [Startup Args] , [CARBON_HOME] /mnt/172.21.0.3/wso2is-5.3.0
identity-server_1  | /usr/local/bin/init.sh: /mnt/172.21.0.3/wso2is-5.3.0/bin/wso2server.sh: /bin/sh^M: bad interpreter: No such file or directory
identity-server_1  | ERROR in /usr/local/bin/init.sh: line 132: exit status of last command: 126
identity-server_1  | Initializing wso2is-5.3.0 in default profile on default platform...
identity-server_1  | Going to sleep for 10s...
identity-server_1  | Successfully updated localMemberHost with 172.21.0.3
identity-server_1  | Creating directory /mnt/172.21.0.3
identity-server_1  | Creating symlink [Target] /mnt/wso2is-5.3.0, [Link] /mnt/172.21.0.3/wso2is-5.3.0
identity-server_1  | Copying artifacts in /mnt/wso2-artifacts to /mnt/172.21.0.3/wso2is-5.3.0
identity-server_1  | Starting wso2is-5.3.0 with [Startup Args] , [CARBON_HOME] /mnt/172.21.0.3/wso2is-5.3.0
identity-server_1  | /usr/local/bin/init.sh: /mnt/172.21.0.3/wso2is-5.3.0/bin/wso2server.sh: /bin/sh^M: bad interpreter: No such file or directory
identity-server_1  | ERROR in /usr/local/bin/init.sh: line 132: exit status of last command: 126
pattern1_identity-server_1 exited with code 1
`
I'm getting this error with current configuration:
 
Server Version: 17.05.0-ce
Storage Driver: devicemapper
Operating System: CentOS Linux 7 (Core)
Kernel: Linux 3.10.0-514.26.2.el7.x86_64
Architecture: x86-64

but if i run this docker-compose project into a vm with Debian 8 
Server Version: 17.03.1-ce
Storage Driver: aufs
it works.
Why?

**Comment by DavidNorena** [comment]
I'm facing the same issue too, but im working on Windows 10 Pro x64

**Comment by DilanUA** [comment]
Closing this since it relates to an implementation before the re-architecturing of the repository which is no longer supported.
