### ISSUE TITLE
Docker version mismatch when building

### ISSUE THREAD

**Issue by HarshaSuranjith** [wso2/docker-is#13]
the build script is complaining that my docker version is old, but I doubt it is the case. Maybe this is not working with community edition ??
 `
$ ./build.sh 
Provisioning Method: default
**Docker version should be equal to or greater than 1.10.0 to build WSO2 Docker images. Found 17.06.1-ce
17.06.1-ce**
Cleaning...
$ docker version 
Client:
 Version:      17.06.1-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   874a737
 Built:        Thu Aug 17 22:51:12 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.1-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   874a737
 Built:        Thu Aug 17 22:50:04 2017
 OS/Arch:      linux/amd64
 Experimental: false
`

any help is much appreciated. thanks

**Comment by lmanohara** [comment]
Hi Harsha,

Seems this is not an issue in your Docker version (17.06.1-CE). We are checking whether the Docker version is supported in the build script and seems that logic is invalid now. You have two solutions for this, either you can comment out [this](https://github.com/wso2/docker-common/blob/7dfdf8e5549c7cf4d4f57dc16b8deeb2c1510c66/scripts/docker-build.sh#L234) line and try to build the Docker image or you can use [Docker compose](https://github.com/wso2/docker-is/tree/release-5.3.0/docker-compose/pattern-1). Also, we have created GitHub issue for this as well https://github.com/wso2/docker-common/issues/16

Thanks,
Lahiru

**Comment by imesh** [comment]
Identity Server Docker image build process will get simplified in #15.

**Comment by DilanUA** [comment]
Closing based on above comment.

**Comment by marcboivin** [comment]
Well still relevant for ESB which doesn't seem to follow the same guidiles as IS.

**Comment by chirangaalwis** [comment]
@marcboivin the build.sh script is not relevant as WSO2 product Docker resources have been simplified in recent times (see https://github.com/wso2/docker-is/issues/13#issuecomment-347135936).

It would be great if you can try out the latest Docker resources for WSO2 Enterprise Integrator (from https://github.com/wso2/docker-ei/tree/master/dockerfiles/ubuntu). Please follow [1] for instructions on the usage of Docker images for WSO2 Enterprise Integrator. If you intend to manually build the Docker images, please follow instructions provided at [2].

[1]: [WSO2 Enterprise Integrator Docker images](https://wso2.com/integration/install/docker/get-started/)
[2]: [GitHub documentation](https://github.com/wso2/docker-ei/blob/master/dockerfiles/ubuntu/README.md)

**Comment by marcboivin** [comment]
@chirangaalwis Thanks for the heads up. I did test the new method with the Alpine Image. Way smoother. Tried it for EI too. 

More intuitive for regular docker people. Appreciate the improvement
