### ISSUE TITLE
wso2is:5.9.0-alpine build failed: WSO2_SERVER_DIST_URL Page not found (404)

### ISSUE THREAD

**Issue by ReneKaesler** [wso2/docker-is#175]
**Description:**
When trying to build the `wso2is-5.9.0-alpine` docker file from source, the build process stops with error code `1`. This happens because in `STEP 22/30` the wget command cant find the `WSO2_SERVER_DIST_URL`.

By Interpolationg the `WSO2_SERVER_DIST_URL` argument by myself, I get the following link:
[https://bintray.com/wso2/binaryGA/download_file?file_path=wso2is-5.9.0.zip](https://bintray.com/wso2/binaryGA/download_file?file_path=wso2is-5.9.0.zip)

...Obviously the url is not available.

**Suggested Labels:**
wso2is:5.9.0-alpine, docker build, WSO2_SERVER_DIST_URL

**Affected Product Version:**
5.9.0

**OS, DB, other environment details and versions:**    
adoptopenjdk/openjdk8:jdk8u222-b10-alpine

**Steps to reproduce:**
docker build -t wso2is:5.9.0-alpine .

**Comment by chirangaalwis** [comment]
@ReneKaesler pardon us. We'll take steps to upload the binary, ASAP, to [1].

[1]: [GA versions of the WSO2 products](https://bintray.com/wso2/binaryGA)

**Comment by chirangaalwis** [comment]
@ReneKaesler please find the uploaded distribution from [1].

[1]: [WSO2 Identity Server version 5.9.0](https://bintray.com/wso2/binaryGA/wso2is-5.9.0)

**Comment by chirangaalwis** [comment]
Closing this issue as per above comment (https://github.com/wso2/docker-is/issues/175#issuecomment-545358217).
