### ISSUE TITLE
[5.5.0] Upgrade IS dockerfile to the latest dockerfile template

### ISSUE THREAD

**Issue by RidmiR** [wso2/docker-is#212]
**Description:**
IS 5.5.0 Dockerfile should change into the latest by changing followings,

- Remove the code for copy JDK and product packs from the files directory
- Get the MySQL connector from Maven central repository

**Suggested Labels:**
Milestone - 5.5.0.8

**Comment by RidmiR** [comment]
Fixed.

**Comment by chirangaalwis** [comment]
Fixed.
