### ISSUE TITLE
Upgrade AdoptOpenJDK 11 version to the latest version - 11.0.9_11

### ISSUE THREAD

**Issue by RidmiR** [wso2/docker-is#260]
**Description:**
The AdoptOpenJDK version updated to the latest version of 11.0.9_11 due to High vulnerabilities detected from the docker image. 

**Sub Task:**
- [x] Upgrade version in Alpine based Docker resources
- [x] Upgrade version in CentOS based Docker resources
- [x] Upgrade version in Ubuntu based Docker resources

**Comment by chirangaalwis** [comment]
Fixed.
